language: objective-c
osx_image: xcode7.1
before_install:
  - brew update
  - brew install carthage
before_script:
  - carthage update --platform=ios
script:
  - xctool test -project VPNOn.xcodeproj -scheme VPNOn -sdk iphonesimulator
